### ISSUE TITLE
EmailDevice ForeignKey related_name

### ISSUE THREAD

**Issue by gjae** [django-otp/django-otp#111]
Hi everyone.
I need make prefetch_related from user model to EmailDevice, but,  i dont find the foreignkey related name. Some idea?

**Comment by some1ataplace** [comment]
In the Django-OTP package, the EmailDevice model is related to the User model through a foreign key field called "user". We can use this field to access the EmailDevice objects related to a User instance and prefetch them to reduce database queries.

Assuming you want to prefetch the related EmailDevice objects when fetching a User instance, you can modify your queryset like this:

```
from django.contrib.auth import get_user_model
from django.db.models.query import Prefetch
from django_otp.models import EmailDevice

User = get_user_model()

# Get user and prefetch related EmailDevice objects
user = User.objects.prefetch_related(Prefetch('emaildevice_set')).get(id=1)

# Access the related EmailDevice objects
for email_device in user.emaildevice_set.all():
    # Do something with the EmailDevice object
    pass
```

Here, we are using the Prefetch class to prefetch the related EmailDevice objects during the query. The first argument to Prefetch is the name of the related model's attribute on the User model ('emaildevice_set' in this case). You can use this attribute to access the related EmailDevice objects for a particular User instance.

Note: It's important to use the correct name for the related model's attribute when using prefetch_related(). In the case of Django-OTP, the EmailDevice model has a related_name attribute of "devices" by default. So, if you used related_name='devices' when you defined the ForeignKey field in your User model, you would need to use Prefetch('devices') instead of Prefetch('emaildevice_set').

Also, keep in mind that prefetch_related() will always perform an additional database query to fetch the related objects. So, while it can be a useful optimization, it's important not to abuse it and to use it only when necessary.
