### ISSUE TITLE
hotp does not always generate a token of n digits

### ISSUE THREAD

**Issue by remi1111** [django-otp/django-otp#151]
hotp can sometimes generate a token of n-1 digits if the nth digit is a 0 due to the modulo:
https://github.com/django-otp/django-otp/blob/c18b38d6d673e1a9bc9b4ecefe5904e9583d4e92/src/django_otp/oath.py#L44

**Comment by psagers** [comment]
This function generates integers, not strings. How these integers get rendered (e.g. with or without leading zeros) is someone else's concern. And since HOTP/TOTP codes are generally only rendered on the client side (e.g. mobile apps), this doesn't seem to come up on the server side.

Is there a particular problem you're having that you suspect this is connected to?

**Comment by remi1111** [comment]
Oh okay I was expecting n digits at all times, but as it is expected behaviour I will have to catch that.
Thanks anyways.
