### ISSUE TITLE
OTPTokenForm - otp_token field error

### ISSUE THREAD

**Issue by dwasyl** [django-otp/django-otp#35]
Hi there,

I had a question question regarding how `OTPTokenForm` processes token errors. I'm trying to add the correct markup to my form, however I've noticed that token error's are returned as `non_field_errors` which means the field doesn't have any direct errors.  Shouldn't a token error be returned as a problem with the `otp_token` field?

Not a huge thing, but could be a more standard way of returning the error?

**Comment by psagers** [comment]
Could probably go either way. As long as the token is syntactically valid, its correctness is arguably a question for the form as a whole. Verifying the token involves looking up the device, making sure it belongs to the given user, and then checking the code against it. If it fails, is it the wrong token for the right device or the right token for the wrong device? You're in murky waters here.

Note especially that the built-in forms are there for convenience in simple situations, especially quick and dirty access for internal users. If you're trying to present a nice UI to people, you'll be better off writing your own forms and views, ideally with a more explicit multi-step workflow, as you see with major identity providers.

**Comment by some1ataplace** [comment]
In the OTPTokenForm provided by django-otp, token errors are indeed returned as non-field errors, which means they are not associated with any specific form field. This is because verifying a token involves more than just checking the syntax of the token itself; it requires looking up the device, making sure it belongs to the given user, and then checking the code against it. This makes the correctness of the token a question for the form as a whole, rather than any specific field.

That being said, the non_field_errors attribute of a form is a standard way of returning errors that are not associated with any specific form field, so this approach is reasonable. If you want to customize how token errors are displayed in your form, you could override the non_field_errors method of the form to customize the error markup as desired.

As for whether token errors should be associated with the otp_token field or not, there is no one-size-fits-all answer to this question, as it depends on the specific use case and the design of the form. If you feel that it makes more sense to associate token errors with the otp_token field in your form, you could potentially create a custom form that overrides the default OTPTokenForm and associates token errors with the otp_token field. To do this, you can define a custom method on the form that performs the token verification and then adds any errors to the otp_token field:

```
from django_otp.forms import OTPTokenForm

class CustomOTPTokenForm(OTPTokenForm):
    def clean(self):
        cleaned_data = super().clean()
        token = cleaned_data.get('otp_token')
        device = self.device

        if token and device:
            if not device.verify_token(token):
                self.add_error('otp_token', 'Invalid token')
        else:
            self.add_error('otp_token', 'Cannot verify token')

        return cleaned_data
```

This custom form class extends the default OTPTokenForm and overrides the clean method to perform the token verification logic. If an invalid token is found, it adds an error message to the otp_token field using the add_error method.

You can then use this custom form in your views or templates instead of the default OTPTokenForm to customize how token errors are displayed.
