### ISSUE TITLE
Support for webauthn in the long run

### ISSUE THREAD

**Issue by beckedorf** [django-otp/django-otp#40]
[Webauthn](https://webauthn.io) may become an important method to make a two-factor-authentication in the next years.

I think, it does not fit into the current structure/process of django-otp and this library. (see https://github.com/django-otp/django-otp-yubikey/issues/2). Are there any plans to get this plugin ready for webauthn in the long run?

**Comment by psagers** [comment]
At present, I'm not aware of anyone making long-term investments in django-otp. The project is stable and maintained, but I'm no longer actively using it. I've been using U2F since before it was Webauthn and reached the same conclusion: the core framework would have to be updated to support it.

If I were still building new things in Django, I would likely start a new authentication project to replace this one. It would incorporate some lessons learned, support Webauthn, and also take a more general approach to coordinating multiple coequal authentication mechanisms.

I would be happy to advise anyone taking on such a project.

**Comment by 9mido** [comment]
https://github.com/Bouke/django-two-factor-auth/pull/408

Someone made a PR in django-two-factor-auth if someone wanted to work off of that. But yea I agree probably better to keep OTP and webauthn separate in their own project. 

Here are some other projects that use webauthn / make it able to be integrated in django:

https://gitlab.com/stavros/django-webauthin

https://github.com/shemigon/django-webauthn

https://github.com/duo-labs/py_webauthn

https://github.com/mkalioby/django-mfa2/

If someone makes a project for webauthn or PR or have a tutorial of how to do it, then please share it here. It would be great to have something that can be similarly integrated like django-otp.

**Comment by xi** [comment]
I want to add to the list: https://github.com/xi/django-mfa3

I use it in production for some months now. It is opinionated, so easy to set up but not very flexible.

**Comment by claudep** [comment]
Note that django-two-factor-auth does support webauthn from version 1.15.

**Comment by Stormheg** [comment]
I really like the low-level approach django-otp takes. It makes it very flexible to integrate in any project. This low-level approach is something I was missing in other packages that implement WebAuthn. (in others words: they are opinionated)

In addition, I am already quite invested in django-otp. Many projects I work on have implemented 2FA flows using django-otp and don't fancy switching to a different package. We'd rather keep using django-otp. It works very well for us.

For this reason I've been working on a plugin for django-otp that implements WebAuthn and tries to adhere to the same low-level philosophy: [django-otp-webauthn](https://github.com/Stormbase/django-otp-webauthn). It's pretty new, with tests and compelling documentation pretty lacking still... but will eventually mature.

Hope it is useful to others.
