### ISSUE TITLE
Sometimes using totp will raise 'Invalid token' but the rest time is 20s.

### ISSUE THREAD

**Issue by EvanLuo42** [django-otp/django-otp#98]
I have make sure that my system time zone is correct. But it is still happened sometimes. Actually it's by chance. Sometimes this bug will happen sometimes will not.

Django version:4.0
Django-otp version: 1.1.3
Log: No raised error, just happened in frontend.

**Comment by weiztech** [comment]
I also have same problem.

Django version:2.2.x
Django-otp version: 1.1.3

**Comment by some1ataplace** [comment]
Yes, that is correct. When using TOTP, the token will change every 30 seconds by default. However, there could be a window of up to 20 seconds where the token is considered valid, even if it is technically for a previous time interval. This is because the TOTP algorithm generates tokens based on the current time, as well as the pre-shared secret key. Therefore, it is possible for a token generated near the end of a time interval to be considered valid for the start of the next interval, and vice versa. 

However, if the token is invalid even after the 20 seconds grace period, then it could be caused by a clock skew issue. This means that the time on the device generating the token is not synchronized with the server running Django-OTP, causing the token to be rejected. To fix this issue, the server and client device times should be checked to ensure they are synchronized.

**Comment by CharisDimaridis** [comment]
@some1ataplace  comment helped me a lot, I had the same issue with my django application. To be more specific, in my Mac and Ubundu server the OTP Auth was working fine and in my windows 11 workstation I was taking invalid token as an error. Turns out, after going and doing sync time in the windows settings and a restart the django server, the OTP Auth was working fine in the windows 11 michine as well. The tick rate was the default of 30 seconds for the token.
